version: '3.8'

services:
  user-service:
    build: ./user-service

    ports:
      - "3001:3001"
    networks:
      - student-portal-network

  attendance-service:
    build: ./attendance-service

    ports:
      - "3002:3002"
    networks:
      - student-portal-network

  result-service:
    build: ./result-service

    ports:
      - "3003:3003"
    networks:
      - student-portal-network

  frontend:
    build: ./frontend
    
    ports:
      - "80:80"
    networks:
      - student-portal-network

networks:
  student-portal-network:
    driver: bridge
