version: '3.8'

services:
  user-service:
    build: ./user-service
    image: student-portal_user-service:latest
    ports:
      - "3001:3001"
    networks:
      - ecommerce-network

  product-service:
    build: ./product-service
    image: student-portal_product-service:latest
    ports:
      - "3002:3002"
    networks:
      - ecommerce-network

  cart-service:
    build: ./cart-service
    image: student-portal_cart-service:latest
    ports:
      - "3003:3003"
    networks:
      - ecommerce-network

  payment-service:
    build: ./payment-service
    image: student-portal_payment-service:latest
    ports:
      - "3004:3004"
    networks:
      - ecommerce-network

  recommendation-service:
    build: ./recommendation-service
    image: student-portal_recommendation-service:latest
    ports:
      - "3005:3005"
    networks:
      - ecommerce-network

  frontend:
    build: ./frontend
    image: student-portal_frontend:latest
    ports:
      - "80:80"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
