version: '3.8'

services:
  user-service:
    build: ./user-service
    image: student-portal_user-service:latest  # Custom image name
    ports:
      - "3001:3001"
    networks:
      - student-portal-network

  attendance-service:
    build: ./attendance-service
    image: student-portal_attendance-service:latest  # Custom image name
    ports:
      - "3002:3002"
    networks:
      - student-portal-network

  result-service:
    build: ./result-service
    image: student-portal_result-service:latest  # Custom image name
    ports:
      - "3003:3003"
    networks:
      - student-portal-network

  frontend:
    build: ./frontend
    image: student-portal_frontend:latest  # Custom image name
    ports:
      - "80:80"
    networks:
      - student-portal-network

networks:
  student-portal-network:
    driver: bridge
